<a href="https://colab.research.google.com/github/mzyada/AndroidTutorialForBeginners/blob/master/notebook36b3848b15_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)



In [37]:
train_data=pd.read_csv("titanic/train.csv")
test_data=pd.read_csv("titanic/test.csv")
Tpredict_data=pd.read_csv("titanic/gender_submission.csv")



In [38]:
trainY=train_data['Survived']




In [39]:
trainX=train_data.drop('Survived',axis=1)

In [40]:
trainX.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Pclass       891 non-null    int64  
 2   Name         891 non-null    object 
 3   Sex          891 non-null    object 
 4   Age          714 non-null    float64
 5   SibSp        891 non-null    int64  
 6   Parch        891 non-null    int64  
 7   Ticket       891 non-null    object 
 8   Fare         891 non-null    float64
 9   Cabin        204 non-null    object 
 10  Embarked     889 non-null    object 
dtypes: float64(2), int64(4), object(5)
memory usage: 76.7+ KB


In [41]:
trainX.drop(['Name','Ticket','Cabin'],axis=1,inplace=True)
test_data.drop(['Name','Ticket','Cabin'],axis=1,inplace=True)


In [43]:
print(trainX.head())
trainX.Embarked.unique()

   PassengerId  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0            1       3    male  22.0      1      0   7.2500        S
1            2       1  female  38.0      1      0  71.2833        C
2            3       3  female  26.0      0      0   7.9250        S
3            4       1  female  35.0      1      0  53.1000        S
4            5       3    male  35.0      0      0   8.0500        S


array(['S', 'C', 'Q', nan], dtype=object)

In [103]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
imputer_num=SimpleImputer(missing_values=np.nan, strategy='mean')
trainX.Embarked = imputer.fit_transform(trainX['Embarked'].values.reshape(-1,1))
trainX.Age = imputer_num.fit_transform(trainX['Age'].values.reshape(-1,1))
test_data.Embarked = imputer.fit_transform(test_data['Embarked'].values.reshape(-1,1))
test_data.Age = imputer_num.fit_transform(test_data['Age'].values.reshape(-1,1))
test_data.Fare = imputer_num.fit_transform(test_data['Fare'].values.reshape(-1,1))

In [104]:
print(trainX.Age.unique())
print(trainX.Embarked.unique())
print(test_data.Embarked.unique())

[22.         38.         26.         35.         29.69911765 54.
  2.         27.         14.          4.         58.         20.
 39.         55.         31.         34.         15.         28.
  8.         19.         40.         66.         42.         21.
 18.          3.          7.         49.         29.         65.
 28.5         5.         11.         45.         17.         32.
 16.         25.          0.83       30.         33.         23.
 24.         46.         59.         71.         37.         47.
 14.5        70.5        32.5        12.          9.         36.5
 51.         55.5        40.5        44.          1.         61.
 56.         50.         36.         45.5        20.5        62.
 41.         52.         63.         23.5         0.92       43.
 60.         10.         64.         13.         48.          0.75
 53.         57.         80.         70.         24.5         6.
  0.67       30.5         0.42       34.5        74.        ]
[2 0 1]
[1 2 0]


In [105]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
trainX['Embarked'] = le.fit_transform(trainX.Embarked)
trainX['Sex'] = le.fit_transform(trainX.Sex)
test_data['Embarked'] = le.fit_transform(test_data.Embarked)
test_data['Sex'] = le.fit_transform(test_data.Sex)


In [106]:
trainX.head()

PassengerId  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0            1       3    1  22.0      1      0   7.2500         2
1            2       1    0  38.0      1      0  71.2833         0
2            3       3    0  26.0      0      0   7.9250         2
3            4       1    0  35.0      1      0  53.1000         2
4            5       3    1  35.0      0      0   8.0500         2

In [107]:
test_data.head()

PassengerId  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0          892       3    1  34.5      0      0   7.8292         1
1          893       3    0  47.0      1      0   7.0000         2
2          894       2    1  62.0      0      0   9.6875         1
3          895       3    1  27.0      0      0   8.6625         2
4          896       3    0  22.0      1      1  12.2875         2

In [108]:
from sklearn.tree import DecisionTreeClassifier, export_graphviz
dt = DecisionTreeClassifier(criterion='entropy')
dt.fit(trainX,trainY)



DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [109]:
dt.feature_importances_

array([0.21654678, 0.09175051, 0.22656221, 0.19955946, 0.04137945,
       0.01889205, 0.19476877, 0.01054077])

In [110]:
dt.score(trainX,trainY)

1.0

In [111]:
dt.score(test_data,Tpredict_data['Survived'])

0.7751196172248804

In [112]:
#dt.score(test_data,Tpredict_data['Survived'])
##test_data[test_data['Embarked'].isnull()] imp